FROM node:17

WORKDIR /app

# Install pm2
RUN npm install pm2 -g

# Install packages
COPY package.json /app
RUN npm install --production

# Copy all other source code to work directory and build
COPY . /app
RUN npm run build

# Run
CMD ./run.sh