FROM node:16

WORKDIR /app

# Install packages
COPY package.json /app
RUN npm install

# Copy all other source code to work directory
# Build TypeScript
COPY . /app
RUN npm run build

# Run
CMD ./run.sh